// redux/features/auth/authErrorCodes.js
export const AUTH_ERROR_CODE = {
  EMAIL_ALREADY_IN_USE: "EMAIL_ALREADY_IN_USE",
  INVALID_CREDENTIAL: "INVALID_CREDENTIAL",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  AUTH_ERROR: "AUTH_ERROR",
  UNKNOWN: "UNKNOWN",
};
